title: Amenra

baseurl: "/amenra"

# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# Compress CSS
sass:
  style: compressed
  sass_dir: _sass

show_excerpts: true # set to true to show excerpts on the homepage

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

# Build settings
markdown: kramdown

# Kramdown options
kramdown:
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/